spring:
  application:
    name: quiz

  datasource:
    url: jdbc:mysql://localhost:3306/winter_quiz
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
